name: Deploy

on:
  push:
    branches:
      - master # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile.pem
        chmod 400 keyfile.pem
        ssh -t -i keyfile.pem ubuntu@ec2-44-211-224-25.compute-1.amazonaws.com "sudo bash deploy.sh"